# Generated by Django 2.2.7 on 2020-11-14 11:27

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[core.models.validate_cpf])),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('chattel', models.IntegerField()),
                ('movables', models.IntegerField()),
                ('profile_type', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.PersonalData')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalData',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('working', models.BooleanField()),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('complement', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('role', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='core.PersonalData')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_monthly_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_account', models.CharField(blank=True, max_length=300, null=True)),
                ('fixed_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('variable_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('account_number', models.BigIntegerField()),
                ('agency', models.IntegerField()),
                ('bank', models.IntegerField()),
                ('digit', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='core.PersonalData')),
            ],
        ),
    ]
